tag_model_mapping = {
    "AHU PDB-1 SPARE": ,
    "AHU PDB-1_INCOMER": ,
    "AHU PDB-2 INCOMER": ,
    "AHU-1": ,
    "AHU-10": ,
    "AHU-2": ,
    "AHU-3": ,
    "AHU-4": ,
    "AHU-5": ,
    "AHU-6": ,
    "AHU-7": ,
    "AHU-8": ,
    "AHU-9": ,
    "AIR COMPRESSOR-1": ,
    "AIR COMPRESSOR-2": ,
    "AIR COMPRESSOR-3": ,
    "AIR COMPRESSOR-4": ,
    "ALOX PECVD MCHINE-1": ,
    "ALOX PECVD MCHINE-2": ,
    "ALOX PECVD MCHINE-3": ,
    "AXIL FLOW FAN": ,
    "CELL LT PANEL-1 INCOMER": ,
    "CELL LT PANEL-2 INCOMER": ,
    "CELL LT PANEL-3 INCOMER": ,
    "CELL LT PANEL-4 INCOMER": ,
    "CELL TOLL PDB-1 INCOMER": ,
    "CELL TOOL PDB PANEL-2 SPARE (9F2)": ,
    "CELL TOOL PDB-2 INCOMER": ,
    "DIFFUSSION-1": ,
    "DIFFUSSION-2": ,
    "DIFFUSSION-3": ,
    "ELECTRICAL PANEL INCOMER": ,
    "HOT WATER TANK-1": ,
    "HOT WATER TANK-2": ,
    "INCOMER UPS 1A": ,
    "INCOMER UPS 1B": ,
    "INCOMER UPS 1C": ,
    "INCOMER UPS 1D": ,
    "INCOMER UPS 1E": ,
    "OG UPS 1A": ,
    "OG UPS 1B": ,
    "OG UPS 1C": ,
    "OG UPS 1D": ,
    "OG UPS 1E": ,
    "OG UPS-1 (SECTION-1)": ,
    "OG UPS-1 (SECTION-2)": ,
    "SINX PECVD MACHINE -1": ,
    "SINX PECVD MACHINE -2": ,
    "SINX PECVD MACHINE -4": ,
    "SINX PECVD MACHINE-3": ,
    "UPS -1 LT PANEL-1 INCOMER": ,
    "UPS -1 LT PANEL-1 PCW": ,
    "UPS-1 LT PANEL-2 INCOMER": ,
