# Generated by Django 5.0.7 on 2024-07-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTFeederReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('app_energy_export', models.FloatField()),
                ('avg_ac_power', models.FloatField()),
                ('avg_app_power', models.FloatField()),
                ('avg_current', models.FloatField()),
                ('avg_pf', models.FloatField()),
                ('avg_rac_power', models.FloatField()),
                ('avg_voltage', models.FloatField()),
                ('b_ac_power', models.FloatField()),
                ('b_app_power', models.FloatField()),
                ('b_current', models.FloatField()),
                ('b_pf', models.FloatField()),
                ('b_rac_power', models.FloatField()),
                ('b_voltage', models.FloatField()),
                ('br_voltage', models.FloatField()),
                ('frequency', models.FloatField()),
                ('pn_voltage', models.FloatField()),
                ('r_ac_power', models.FloatField()),
                ('r_app_power', models.FloatField()),
                ('r_current', models.FloatField()),
                ('r_pf', models.FloatField()),
                ('r_rac_power', models.FloatField()),
                ('r_voltage', models.FloatField()),
                ('ry_voltage', models.FloatField()),
                ('thd_voltage_an', models.FloatField()),
                ('thd_voltage_cn', models.FloatField()),
                ('thd_voltage_en', models.FloatField()),
                ('today_app_energy_export', models.FloatField()),
                ('today_export', models.FloatField()),
                ('today_import', models.FloatField()),
                ('total_export', models.FloatField()),
                ('total_import', models.FloatField()),
                ('y_ac_power', models.FloatField()),
                ('y_app_power', models.FloatField()),
                ('y_current', models.FloatField()),
                ('y_pf', models.FloatField()),
                ('y_rac_power', models.FloatField()),
                ('y_voltage', models.FloatField()),
                ('yb_voltage', models.FloatField()),
                ('yes_app_energy_export', models.FloatField()),
                ('yes_export', models.FloatField()),
                ('yes_import', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InverterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ac_power', models.FloatField()),
                ('b_ac_power', models.FloatField()),
                ('b_current', models.FloatField()),
                ('b_voltage', models.FloatField()),
                ('br_voltage', models.FloatField()),
                ('dc_current', models.FloatField()),
                ('dc_power', models.FloatField()),
                ('dc_voltage', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('fault', models.CharField(max_length=255)),
                ('frequency', models.FloatField()),
                ('inv_fault_subcode', models.CharField(max_length=255)),
                ('inv_warning_bit_h', models.IntegerField()),
                ('inv_warning_subcode', models.IntegerField()),
                ('peak_power', models.FloatField()),
                ('pf', models.FloatField()),
                ('pv1_current', models.FloatField()),
                ('pv1_dc_current', models.FloatField()),
                ('pv1_dc_power', models.FloatField()),
                ('pv1_dc_voltage', models.FloatField()),
                ('pv1_voltage', models.FloatField()),
                ('pv10_current', models.FloatField()),
                ('pv10_voltage', models.FloatField()),
                ('pv11_current', models.FloatField()),
                ('pv11_voltage', models.FloatField()),
                ('pv12_current', models.FloatField()),
                ('pv12_voltage', models.FloatField()),
                ('pv13_current', models.FloatField()),
                ('pv13_voltage', models.FloatField()),
                ('pv14_current', models.FloatField()),
                ('pv14_voltage', models.FloatField()),
                ('pv15_current', models.FloatField()),
                ('pv15_voltage', models.FloatField()),
                ('pv16_current', models.FloatField()),
                ('pv16_voltage', models.FloatField()),
                ('pv17_current', models.FloatField()),
                ('pv17_voltage', models.FloatField()),
                ('pv18_current', models.FloatField()),
                ('pv18_voltage', models.FloatField()),
                ('pv19_current', models.FloatField()),
                ('pv19_voltage', models.FloatField()),
                ('pv2_current', models.FloatField()),
                ('pv2_dc_current', models.FloatField()),
                ('pv2_dc_power', models.FloatField()),
                ('pv2_dc_voltage', models.FloatField()),
                ('pv2_voltage', models.FloatField()),
                ('pv20_current', models.FloatField()),
                ('pv20_voltage', models.FloatField()),
                ('pv3_current', models.FloatField()),
                ('pv3_dc_current', models.FloatField()),
                ('pv3_dc_power', models.FloatField()),
                ('pv3_dc_voltage', models.FloatField()),
                ('pv3_voltage', models.FloatField()),
                ('pv4_current', models.FloatField()),
                ('pv4_dc_current', models.FloatField()),
                ('pv4_dc_power', models.FloatField()),
                ('pv4_dc_voltage', models.FloatField()),
                ('pv4_voltage', models.FloatField()),
                ('pv5_current', models.FloatField()),
                ('pv5_dc_current', models.FloatField()),
                ('pv5_dc_power', models.FloatField()),
                ('pv5_dc_voltage', models.FloatField()),
                ('pv5_voltage', models.FloatField()),
                ('pv6_current', models.FloatField()),
                ('pv6_dc_current', models.FloatField()),
                ('pv6_dc_power', models.FloatField()),
                ('pv6_dc_voltage', models.FloatField()),
                ('pv6_voltage', models.FloatField()),
                ('pv7_current', models.FloatField()),
                ('pv7_dc_current', models.FloatField()),
                ('pv7_dc_power', models.FloatField()),
                ('pv7_dc_voltage', models.FloatField()),
                ('pv7_voltage', models.FloatField()),
                ('pv8_current', models.FloatField()),
                ('pv8_dc_current', models.FloatField()),
                ('pv8_dc_power', models.FloatField()),
                ('pv8_dc_voltage', models.FloatField()),
                ('pv8_voltage', models.FloatField()),
                ('pv9_current', models.FloatField()),
                ('pv9_voltage', models.FloatField()),
                ('r_ac_power', models.FloatField()),
                ('r_current', models.FloatField()),
                ('r_voltage', models.FloatField()),
                ('ry_voltage', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('temp', models.FloatField()),
                ('today_energy', models.FloatField()),
                ('total_energy', models.FloatField()),
                ('total_strings_current', models.FloatField()),
                ('y_ac_power', models.FloatField()),
                ('y_current', models.FloatField()),
                ('y_voltage', models.FloatField()),
                ('yb_voltage', models.FloatField()),
                ('yest_energy', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LTPanelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('app_energy', models.FloatField()),
                ('avg_current', models.FloatField()),
                ('avg_line_voltage', models.FloatField()),
                ('avg_phase_voltage', models.FloatField()),
                ('avg_power_factor', models.FloatField()),
                ('b_active_power', models.FloatField()),
                ('b_app_power', models.FloatField()),
                ('b_current', models.FloatField()),
                ('b_phase_voltage', models.FloatField()),
                ('b_reactive_power', models.FloatField()),
                ('br_voltage', models.FloatField()),
                ('frequency', models.FloatField()),
                ('lag_import', models.FloatField()),
                ('r_active_power', models.FloatField()),
                ('r_app_power', models.FloatField()),
                ('r_current', models.FloatField()),
                ('r_phase_voltage', models.FloatField()),
                ('r_reactive_power', models.FloatField()),
                ('ry_voltage', models.FloatField()),
                ('today_app_energy', models.FloatField()),
                ('today_export', models.FloatField()),
                ('today_import', models.FloatField()),
                ('total_energy_export', models.FloatField()),
                ('total_energy_import', models.FloatField()),
                ('total_reactive_power', models.FloatField()),
                ('y_active_power', models.FloatField()),
                ('y_app_power', models.FloatField()),
                ('y_current', models.FloatField()),
                ('y_current_demo', models.FloatField()),
                ('y_phase_voltage', models.FloatField()),
                ('y_power_factor', models.FloatField()),
                ('y_reactive_power', models.FloatField()),
                ('yb_voltage', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='P2_HT_Incomer',
            fields=[
                ('htfeederreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.htfeederreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.htfeederreading',),
        ),
        migrations.CreateModel(
            name='P2_HT_OG1',
            fields=[
                ('htfeederreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.htfeederreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.htfeederreading',),
        ),
        migrations.CreateModel(
            name='P2_HT_OG2',
            fields=[
                ('htfeederreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.htfeederreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.htfeederreading',),
        ),
        migrations.CreateModel(
            name='P2_HT_OG3',
            fields=[
                ('htfeederreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.htfeederreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.htfeederreading',),
        ),
        migrations.CreateModel(
            name='P2_HT_OG4',
            fields=[
                ('htfeederreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.htfeederreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.htfeederreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU1',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU10',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU11',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU12',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU13',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU2',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU3',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU4',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_AHU9',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEIPLCELL_PCC3',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_PEPLCELL_LTP3',
            fields=[
                ('inverterreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.inverterreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.inverterreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU10',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU11',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU3',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU4',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU5',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU6',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU7',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU8',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_AHU9',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AHUPDB_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF1_DG1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF1_DG2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF1_TF1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF1_TF2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF2_DG3',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF2_DG4',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF2_TF3',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_AMF2_TF4',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_Diffusion1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_Diffusion2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_Diffusion3',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_Diffusion4',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_EXTDIHeater1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_EXTDIHeater2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_EXTDIHeater21',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_EXTDIHeater22',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP1_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP2_ALOXP1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP2_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP2_PostAnnealing1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP2_PostAnnealing2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP2_SINXP1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP2_SINXP2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP2_SINXP3',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP3_AHU12',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP3_AHU13',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellLTP3_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB1_ALOXP2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB1_ALOXP3',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB1_HotWaterTank1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB1_HotWaterTank2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB1_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB1_PreAnnealing1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB1_PreAnnealing2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB2_1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_CellToolPDB2_2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_LTP4AirCompressor1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_LTP4AirCompressor2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_LTP4AirCompressor3',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_LTP4AirCompressor4',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_LTP4AirCompressor_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC1_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC2_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC3_AHUPDB1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC3_Chiller1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC3_CTCWPPanel',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC3_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC3_UPS2A2B',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC4_Chiller',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC4_ETPDB',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_PCC4_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPS1_UOG1A',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPS1_UOG1B',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPS1_UOG1C',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPS1_UOG1D',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPS2_UOG2A',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPS2_UOG2B',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPS2_UOG2C',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT1_Alkaline1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT1_Alkaline2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT1_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT1_Texture1',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT1_Texture2',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT2_ExhaustSystem',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT2_Incomer',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
        migrations.CreateModel(
            name='P2_UPSLT2_PCW',
            fields=[
                ('ltpanelreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PEIPL.ltpanelreading')),
            ],
            options={
                'abstract': False,
            },
            bases=('PEIPL.ltpanelreading',),
        ),
    ]
